# Generated by Django 3.1.7 on 2021-03-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20210330_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_modified',
            new_name='updated_on',
        ),
    ]
