# Generated by Django 3.2 on 2021-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-uploaded_date',)},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='uploaded_date',
        ),
        migrations.AddField(
            model_name='document',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='classification',
            field=models.CharField(choices=[('formal', 'Formal'), ('informal', 'Informal')], default='informal', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(),
        ),
    ]
