# Generated by Django 3.2 on 2021-04-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_document_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='owner_id',
        ),
        migrations.AlterField(
            model_name='document',
            name='classification',
            field=models.CharField(choices=[('official', 'Official'), ('unofficial', 'Unofficial')], default='informal', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
