# Generated by Django 3.1.7 on 2021-04-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('F', 'formal'), ('INF', 'informal')], default='INF', max_length=3)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
